### ISSUE TITLE
warning=Not yet supported platform

### ISSUE THREAD

**Issue by songproducer** [simplestaking/tezos-opam-builder#4]
When running:
>./run.sh node

I got:
> warning=Not yet supported platform: 'OSInformation { os_type: OSX, version: "10.15.1" }', requested artifact_for_platform: None!
--- stderr
thread 'main' panicked at 'Not yet supported platform!', tezos/interop/build.rs:95:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
   Compiling riker v0.3.2
   Compiling librocksdb-sys v6.1.4
   Compiling riker v0.3.2 (https://github.com/simplestaking/riker.git?branch=slog-support#84a58eaf)
   Compiling tezos_api v0.1.0 (/Users/leotreasure/tezedge/tezos/api)
   Compiling tezos_wrapper v0.1.0 (/Users/leotreasure/tezedge/tezos/wrapper)
   Compiling riker-patterns v0.3.2
   Compiling networking v0.1.0 (/Users/leotreasure/tezedge/networking)
   Compiling rocksdb v0.12.4
   Compiling storage v0.1.0 (/Users/leotreasure/tezedge/storage)
   Compiling shell v0.1.0 (/Users/leotreasure/tezedge/shell)
   Compiling rpc v0.1.0 (/Users/leotreasure/tezedge/rpc)
   Compiling monitoring v0.1.0 (/Users/leotreasure/tezedge/monitoring)
   Compiling light-node v0.1.0 (/Users/leotreasure/tezedge/light_node)
    Finished dev [unoptimized + debuginfo] target(s) in 3m 03s
     Running `target/debug/light-node -d /tmp/tezedge -B /tmp/tezedge --network babylonnet --protocol-runner ./target/debug/protocol-runner`
error: Invalid value for '--protocol-runner <PATH>': Tezos protocol runner executable not found at './target/debug/protocol-runner'

**Comment by mrjoe7** [comment]
Hi, at the moment we do not support OSX build. This is because we are linking the original Tezos node which is written in OCaml and we need to build binary of shared library for each platform.
But you can run tezedge node in docker:
```sh
docker run simplestakingcom/tezedge-node
```

**Comment by mrjoe7** [comment]
I updated the `run.sh` script in https://github.com/simplestaking/tezedge to launch node in docker.
```
./run.sh docker
```
