### ISSUE TITLE
Ubuntu 21.04

### ISSUE THREAD

**Issue by royscheeren** [simplestaking/tezos-opam-builder#5]
Hi,

I tried to build TezEdge on my raspberry pi 4 with Ubuntu 21.04 installed. But it failed with message 
`No precompiled library found for 'OSInformation { os+type: Ubuntu, version "21.04" }'`

**Comment by bkontur** [comment]
@royscheeren 
Hello, we had a problem with dockerhub and lower 19.x docker, where ubuntu21 fails, but meantime it was upgraded to 20.x, so we finally added support for ubuntu21.
I dont know how you tried to run it, so please, update TezEdge git to our latest version (v1.9.0)
